# Generated by Django 5.0.3 on 2026-05-16 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_copytradingprofile_copytradingfollower_cryptoswap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentconfirmation',
            name='activated_investment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_confirmation', to='investments.activeinvestment'),
        ),
    ]
