# Generated by Django 5.0.3 on 2026-05-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentwallet',
            name='logo_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='paymentwallet',
            name='qr_code',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
