# Generated by Django 5.0.3 on 2026-05-11 00:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_paymentwallet_logo_url_paymentwallet_qr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_email', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=150)),
                ('activity_type', models.CharField(choices=[('registration', 'User Registration'), ('login', 'User Login'), ('investment', 'Investment Created'), ('payment_pending', 'Payment Pending'), ('payment_confirmed', 'Payment Confirmed'), ('payment_rejected', 'Payment Rejected'), ('withdrawal_requested', 'Withdrawal Requested'), ('withdrawal_processed', 'Withdrawal Processed'), ('referral', 'Referral Reward'), ('copy_trade', 'Copy Trading Started'), ('swap', 'Crypto Swap'), ('wallet_import', 'Wallet Imported')], max_length=30)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('plan_name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_email'], name='admin_panel_user_em_2b83a4_idx'), models.Index(fields=['activity_type'], name='admin_panel_activit_76b2a8_idx'), models.Index(fields=['status'], name='admin_panel_status_b289f9_idx')],
            },
        ),
    ]
