# Generated by Django 5.0.3 on 2026-05-16 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_importedwallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='network',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
